# Generated by Django 4.2.7 on 2023-11-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_team_members'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
            preserve_default=False,
        ),
    ]
