# Generated by Django 4.2.7 on 2023-11-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_team_members'),
        ('contacts', '0002_contact_car_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='car_title',
        ),
        migrations.AlterField(
            model_name='contact',
            name='car_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car'),
        ),
    ]
