# Generated by Django 4.2 on 2023-11-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_car_title_alter_contact_car_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='car_details',
        ),
    ]
