# Generated by Django 4.2 on 2023-11-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_location',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='car_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='car_title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
