# Generated by Django 4.2.7 on 2023-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_car_location_contact_car_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='car_location',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
