# Generated by Django 4.2.7 on 2023-11-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='car_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='car_price',
            field=models.IntegerField(),
        ),
    ]
