# Generated by Django 4.2.7 on 2023-11-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_created_date_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
