# Generated by Django 4.2.7 on 2023-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_city_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='off_price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
