# Generated by Django 4.2.7 on 2023-11-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_off_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='off_price',
            field=models.IntegerField(),
        ),
    ]
