# Generated by Django 4.2 on 2023-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='transition',
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default=None),
            preserve_default=False,
        ),
    ]
