# Generated by Django 4.2 on 2023-11-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_transition_car_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmission',
            new_name='transition',
        ),
    ]
